language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python: 3.7

env: FC=gfortran

addons:
  apt:
#    sources: ubuntu-toolchain-r-test
    packages: gfortran

matrix:
  include:
  - os: linux

install:
  - cd $TRAVIS_BUILD_DIR/build
  - cmake ..
  - cmake --build .

script: ctest --output-on-failure

