language: python
group: travis_latest

git:
  depth: 25
  quiet: true

python: 3.8

env: FC=gfortran

addons:
  apt:
#    sources: ubuntu-toolchain-r-test
    packages: gfortran

matrix:
  include:
  - os: linux

before_install: pip install cmake

install:
- cmake -B build
- cmake --build build

script:
- cd build
- ctest -V
