name: ci

on:
  push:
    paths:
      - "**.f90"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install pytest

    - run: cmake -B build
    - run: cmake --build build

    - run: ctest --output-on-failure
      working-directory: build
