name: ci

on:
  push:
    paths:
      - "**.f90"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default
